/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Qaliel.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Qaliel_Geo_group002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="hair_cinematic_geo_group">
            <group name="hair_front_geo_group">
              <group name="group1" />
              <group name="group2" />
              <group name="group3" />
            </group>
            <group name="hair_side_layer1_geo_group" />
            <group name="hair_side_layer2_geo_group" />
            <group name="hair_side_layer3_geo_group">
              <mesh name="L_polySurface15" geometry={nodes.L_polySurface15.geometry} material={materials.Qaliel_t1} position={[0.23, 23.63, -174.74]} rotation={[0.54, 0, 0]} />
            </group>
            <group name="hair_side_layer4_geo_group" />
            <group name="hair_side_layer5_geo_group" />
            <group name="hair_thin_geo_group">
              <group name="group6" />
              <group name="group9" />
            </group>
          </group>
        </group>
        <group name="group" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Root_joint} />
          <primitive object={nodes.Jophiel_Root_joint} />
          <group name="Geometri_New_4_Jophiel" />
          <group name="Geometri_New_4_Jophiel_evil_clone" />
          <group name="Qaliel_Geo_group001">
            <group name="_Weapons001" />
          </group>
          <group name="body_gameplay001">
            <skinnedMesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials.Qaliel_t2} skeleton={nodes.Mesh003.skeleton} />
            <skinnedMesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials.Qaliel_t3} skeleton={nodes.Mesh003_1.skeleton} />
            <skinnedMesh name="Mesh003_2" geometry={nodes.Mesh003_2.geometry} material={materials.Qaliel_t2} skeleton={nodes.Mesh003_2.skeleton} />
          </group>
          <skinnedMesh name="buckle_low001" geometry={nodes.buckle_low001.geometry} material={materials.Qaliel_t3} skeleton={nodes.buckle_low001.skeleton} />
          <group name="eyes_gameplay001">
            <skinnedMesh name="Mesh019" geometry={nodes.Mesh019.geometry} material={materials.Qaliel_t2} skeleton={nodes.Mesh019.skeleton} />
            <skinnedMesh name="Mesh019_1" geometry={nodes.Mesh019_1.geometry} material={materials.Qaliel_eyes} skeleton={nodes.Mesh019_1.skeleton} />
          </group>
          <skinnedMesh name="FullSword001" geometry={nodes.FullSword001.geometry} material={materials.Sword} skeleton={nodes.FullSword001.skeleton} />
          <skinnedMesh name="Halo001" geometry={nodes.Halo001.geometry} material={materials.Qaliel_t3} skeleton={nodes.Halo001.skeleton} />
          <skinnedMesh name="lion_shoulders001" geometry={nodes.lion_shoulders001.geometry} material={materials.Qaliel_t3} skeleton={nodes.lion_shoulders001.skeleton} />
          <skinnedMesh name="Neck_Collar001" geometry={nodes.Neck_Collar001.geometry} material={materials.Qaliel_t3} skeleton={nodes.Neck_Collar001.skeleton} />
          <skinnedMesh name="Skirt001" geometry={nodes.Skirt001.geometry} material={materials.Qaliel_t3} skeleton={nodes.Skirt001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Qaliel.glb')
